application: infinite-diary
version: 1
runtime: python27
api_version: 1
instance_class: F2
threadsafe: true
skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^backup/.*

handlers:
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
- url: /assets
  static_dir: static
- url: /backup/.*
  script: backup.app
- url: /.*
  script: diary.app
  login: admin

libraries:
- name: jinja2
  version: latest

inbound_services:
- mail
